name: 'coverage'
on:
    pull_request:
    push:
        branches:
            - master
            - main
jobs:
    coverage-visualization:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: ArtiomTr/jest-coverage-report-action@v2
    
    coverage-report:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - run: npm i
            - run: npm run coverag