name: Ejecutar pruebas

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Repository checkout
        uses: actions/checkout@v3

      - name: Install depencies
        run: npm install

      - name: Run test
        run: npm run test

      - name: Run coverage
        run: npm run coverage
